version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: logiclike-postgres
    environment:
      POSTGRES_DB: logiclike_voting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: logiclike-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: logiclike_voting
      DB_USER: postgres
      DB_PASSWORD: password
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: logiclike-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
